# Generated by Django 4.1.2 on 2022-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(max_length=300)),
                ('material', models.CharField(max_length=300)),
                ('costo', models.FloatField()),
                ('existencia', models.IntegerField()),
            ],
        ),
    ]
