# Generated by Django 4.1.2 on 2022-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(max_length=300)),
                ('material', models.CharField(max_length=300)),
                ('costo', models.IntegerField()),
                ('existencia', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
