# Generated by Django 4.1.2 on 2022-11-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_nproducto_delete_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nproducto',
            new_name='Producto',
        ),
    ]
