# Generated by Django 4.1.1 on 2022-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_producto_costo_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(),
        ),
    ]
