# Generated by Django 4.1.1 on 2022-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_producto_costo_alter_producto_existencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.CharField(max_length=300),
        ),
    ]
