# Generated by Django 4.1.1 on 2022-11-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_producto_costo_alter_producto_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
